select * 
from customer;

--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) as revenue
from customer
group by gender
order by revenue desc;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased,Round(avg(review_rating),1) as avg_rating
from customer
group by item_purchased
order by avg_rating desc
fetch first 5 rows only;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,
     Round(avg(purchase_amount),2) as Avg_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type
order by Avg_amount desc;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status,
     count(customer_id) as total_customers,
     round(avg(purchase_amount),2) as avg_spend,
     round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue desc,
     Avg_spend desc;
     
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(
           100 * SUM(
               CASE
                   WHEN discount_applied = 'Yes' THEN 1
                   ELSE 0
               END
           ) / COUNT(*), 2
       ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
FETCH FIRST 5 ROWS ONLY;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

WITH customer_type AS
(
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)

SELECT
    customer_segment,
    COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment
ORDER BY COUNT(*) DESC;

--Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
    subscription_status,
    COUNT(*) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers DESC;

--Q10. What is the revenue contribution of each age group? 

SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue 
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;